### ISSUE TITLE
`cage status` emphásis on the wrong sylláble

### ISSUE THREAD

**Issue by seamusabshere** [faradayio/cage#49]
<img width="338" alt="screen shot 2016-10-27 at 4 53 15 pm" src="https://cloud.githubusercontent.com/assets/15787/19785160/64684b0c-9c66-11e6-94b1-35688a54180e.png">

i would argue that you should leave everything the default color EXCEPT exceptional things (EXIT, STOPPED, etc.)

for example, green RUNNING is the normal state, it should be unexceptional

and the pod/service names are hard to read

**Comment by dkastner** [comment]
I'd like to add to this the task of having more concise/clear output and combine `cage source ls` into `cage status`.

Proposed format:

```
     POD       SERVICE     STATUS      IMAGE           LOCAL     REMOTE                            VOLUMES
placeholders
               db         unmounted    postgresql      <none>    <none>
               redis      unmounted    redis           <none>    <none>
web
               api        mounted      myorg/api       src/api   git://github.com/myorg/api        mylib:src/mylib
               ui         unmounted    myorg/ui        src/ui    git://github.com/myorg/ui
               ui_beta    unmounted    myorg/ui_beta   src/ui    git://github.com/myorg/ui#beta
```

**Comment by emk** [comment]
@dkastner The mounted/unmounted state in that design is too simple, because of the ability to mount extra libraries into multiple containers.

**Comment by emk** [comment]
@dkastner If you'd like to propose a major overhaul of the output, please feel free to file a separate RFC issue with a design. This issue will be closed once I reduce the coloring a bit.

**Comment by emk** [comment]
@seamusabshere I've removed the green from "enabled" (because it's the normal case) and I've made the pods and the services the same color to better support Mac terminals. I'm keeping the bright green for "RUNNING" (because I want it, and it's not the default case, which is is "not running at all"). I'm also keeping a single shade of blue for pod and services names, and we can see how it looks on a variety of screens this week.

A sample:

![cage-status-less-color](https://cloud.githubusercontent.com/assets/36963/20274908/698e7a96-aa64-11e6-8bc8-6b57a77ad916.png)
