### ISSUE TITLE
Add command for tailing logs

### ISSUE THREAD

**Issue by dkastner** [faradayio/cage#7]

**Comment by emk** [comment]
Could we spec out some ideas about how this might work in an ideal world? We don't have to implement all right away, but I'd like to get the API right.

Here's my proposal for the final API:

```sh
cage logs [<pods_or_services>...]
```

This covers a number of cases:

- _If it displays logs for more than one container, it annotes each line with the container name._
- With no args, it displays interleaved logs for all containers.
- With a pod name, it displays the logs for all containers in that pod.
- With either `pod/service` or a unique service name, it displays the logs for that service.

**Comment by emk** [comment]
The standard Docker tools include the following options:

```
Usage:	docker logs [OPTIONS] CONTAINER

Fetch the logs of a container

Options:
      --details        Show extra details provided to logs
  -f, --follow         Follow log output
      --help           Print usage
      --since string   Show logs since timestamp
      --tail string    Number of lines to show from the end of the logs (default "all")
  -t, --timestamps     Show timestamps
```

```
docker-compose logs --help
View output from containers.

Usage: logs [options] [SERVICE...]

Options:
    --no-color          Produce monochrome output.
    -f, --follow        Follow log output.
    -t, --timestamps    Show timestamps.
    --tail="all"        Number of lines to show from the end of the logs
                        for each container.
```

**Comment by emk** [comment]
@dkastner Let me fix #8 first (the new argument-parsing scheme), and then you can go ahead and implement any subset of this that you want to work on.

**Comment by emk** [comment]
The fancier, multi-container versions of this might benefit from #9, which would make it easier to multiplex tagged I/O from multiple threads or external processes. But that doesn't need to block the initial implementation.

**Comment by emk** [comment]
OK, I've added a `project.pod_or_service(name)` function which can be used to look up either a pod or a service to print the logs from. This will allow you to easily implement:

```sh
cage logs <POD_OR_SERVICE>
```

I wouldn't worry about the multi-pod / multi-service version of this command yet, because doing a good job of that depends on #9, which I want to poke at some more.

To implement this, I would recommend doing the following:

1. Edit `src/cli.yml` to add a new `logs` subcommand with appropriate arguments. See the [clap documentation](https://github.com/kbknapp/clap-rs).
2. Dispatch the new arguments in `src/main.rs` to your new `src/cmd/logs.rs`. This should look like:
    ```rust
    pub trait CommandLogs {
        /// Up all the images in the specified pods.
        fn logs<CR>(&self, runner: &CR, ovr: &Override, pod_or_service_name: &str) -> Result<()>
            where CR: CommandRunner;
    }
    ```
3. From inside that function, call `match try!(self.pod_or_service_or_err(pod_or_service_name)) { ... }` and handle both the `PodOrService::Pod` and the `PodOrService::Service` case.

**Comment by emk** [comment]
Also, if you want to pass through any arguments, you can add a new `args::opts::Logs` structure to `src/args/opts.rs`, based on the ones already there (but ignore the `Deref` hack; that's going away shortly) and implement `ToArgs` and add method to `ArgMatchesExt` in `src/main.rs` that builds your `args::opts::Logs` structure based on the `ArgMatches` structure from clap.

If you have any questions, please let me know!

**Comment by emk** [comment]
There are also new goodies in 488bf19 which might be of interest. Although you probably can't use the `compose` command directly, it would be easy to make a single-item wrapper around it.
